export enum PATH {
  PACKS = '/packs',
  CARDS = '/cards',
  CARDS_ID = '/cards/:id',
  PROFILE = '/profile',
  LOGIN = '/login',
  RECOVERY = '/recovery',
  CHECK_EMAIL = '/check_email',
  REGISTRATION = '/registration',
  NEW_PASSWORD = '/new_password',
  NEW_PASSWORD_TOKEN = '/new_password/:token',
  PAGE_NOT_FOUND = '/404',
  LEARN = '/learn',
  LEARN_PACK_ID = '/learn/:packId',
}
